---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-{{ .Release.Name }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: serendipity-{{ .Release.Name }}
      tier: backend
  template:
    metadata:
      labels:
        app: serendipity-{{ .Release.Name }}
        tier: backend
    spec:
      containers:
        - name: backend-{{ .Release.Name }}
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-{{ .Release.Name }}
spec:
  selector:
    app: serendipity-{{ .Release.Name }}
    tier: backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: 3000