apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress-{{ .Release.Name }}
spec:
  rules:
  - http:
      paths:
      - path: "{{ .Values.application.ingress.path }}"
        pathType: Prefix
        backend:
          service:
            name: backend-{{ .Release.Name }}
            port:
              number: {{ .Values.application.ingress.port }}