apiVersion: batch/v1
kind: CronJob
metadata:
  name: sharing-expiration-{{ .Release.Name }}
spec:
  schedule: "15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: expirer-{{ .Release.Name }}
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - curl 
            - backend-{{ .Release.Name }}/validateSharings
          restartPolicy: OnFailure
