name: Deploy

on:
  push:
    tags:
      - "v*"  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get kubeconfig
        run: |
          aws eks --region us-east-1 update-kubeconfig --name Serendipity --alias serendipity
          kubectl config set-context --current 
      - name: Apply helm charts
        run: |
          helm upgrade --install prod deploy --set backend.tag=${{ github.sha }} 