name: Deploy

on:
  push:
    tags:
      - "v*"  
jobs:
  deploy:
    name: Mono Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start container
        uses: appleboy/ssh-action@master
        with:
          host: ec2-18-215-172-111.compute-1.amazonaws.com
          username: ec2-user
          key: ${{ secrets.KEY }}
          script: |
            sudo docker stop server 
            sudo docker rm server
            sudo docker run -d --publish=80:3000 --name=server ghcr.io/osimon8/cis400:${{ github.sha }}
            sudo docker exec server sh -c "echo \"${{ secrets.DB_CONFIG }}\" > secrets/rds.js"
            sudo docker exec server sh -c "echo \"${{ secrets.ENCRYPT }}\" > secrets/encrypt.js"
